### ISSUE TITLE
Minor Typos + Pinching

### ISSUE THREAD

**Issue by jeremyle56** [imagine-hussain/math2111_notes#12]
Hi here are a few potential typos I noticed while reading your notes for the first 3 weeks of the course. 

![image](https://user-images.githubusercontent.com/112688727/222959557-1eab2065-9a3a-41e2-b896-81ddc369bfce.png)
I don't think that should be there.

![image](https://user-images.githubusercontent.com/112688727/222959592-a55ec059-57ad-40c0-912c-380047704ddf.png)
In 1.5, forgot the slash for command. 

![image](https://user-images.githubusercontent.com/112688727/222959876-dc90c81c-21c1-40e4-80c7-0f2d3a61e781.png)
Full stops on a new line. Put full stops in the equation mode?

![image](https://user-images.githubusercontent.com/112688727/222959688-ebf7ad59-372b-4cfe-b064-bcfbfae3513b.png)
Crazy subscript brackets?

![image](https://user-images.githubusercontent.com/112688727/222960003-89ca149c-9509-46bf-90a9-f923f5a7a530.png)
Should there be full stops here? Also Taylor's Theorem has $f^{(n)}(a)$ not $f^{(n)}(x)$ in the sum. I believe the remainder has $(x-a)^{k+1}$ instead of $(x-a)^k$.

Noticed that your Pinching Theorem was empty, this is what I have if you wanted to use it.
```tex
\paragraph{Pinching Theorem}
Let \(\Omega \subset \mathbb{R}^n\), let \(\textbf{a}\) be a limit point of \(\Omega\)
and let \(f,g ,h: \Omega \rightarrow \mathbb{R}\) be functions such that there exists
\(\epsilon > 0\) such that 
\[
    g(\textbf{x}) \leq f(\textbf{x}) \leq h(\textbf{x}) \qquad
    \forall \textbf{x} \in B(\textbf{a}, \epsilon) \cap \Omega.
\] 
Then
\[
    \lim_{x\to \textbf{a}} g(\textbf{x}) = \textbf{b} = \lim_{x\to \textbf{a}} h(\textbf{x}) 
    \implies \lim_{x\to \textbf{a}} f(\textbf{x}) = \textbf{b}.
\]
```
Let me know if any of this is wrong.

**Comment by jeremyle56** [comment]
![image](https://user-images.githubusercontent.com/112688727/222961937-9a3f9a19-9191-4960-82f7-2d9547cb7d84.png)
Could also make these vertical dots, but isn't really a typo.

**Comment by jeremyle56** [comment]
![image](https://user-images.githubusercontent.com/112688727/223050893-49e5c93e-0bfd-4890-8466-ef941b93b1fb.png)
The bottom row is incorrect. Should be 
```tex
\dfrac{\partial^2 f}{\partial x_1 \partial x_n} & \dfrac{\partial^2 f}{\partial x_2 \partial x_n} & \cdots &\dfrac{\partial^2 f}{\partial x_n \partial x_n} \\
```

**Comment by imagine-hussain** [comment]
> Crazy subscript brackets?

I did `D_(f_(a))g` instead of `D_{f(a)}g`.

**Comment by imagine-hussain** [comment]
> Noticed that your Pinching Theorem was empty, this is what I have if you wanted to use it.

I just got lazy here because it was assumed knowledge. But thank you, I will insert this in.

**Comment by imagine-hussain** [comment]
> ![image](https://user-images.githubusercontent.com/112688727/223050893-49e5c93e-0bfd-4890-8466-ef941b93b1fb.png) The bottom row is incorrect. Should be
> 
> ```
> \dfrac{\partial^2 f}{\partial x_1 \partial x_n} & \dfrac{\partial^2 f}{\partial x_2 \partial x_n} & \cdots &\dfrac{\partial^2 f}{\partial x_n \partial x_n} \\
> ```

good catch!

**Comment by imagine-hussain** [comment]
> ![image](https://user-images.githubusercontent.com/112688727/222961937-9a3f9a19-9191-4960-82f7-2d9547cb7d84.png) Could also make these vertical dots, but isn't really a typo.

I'll make them vertical dots. At this time, i had `...` expanding into `\cdots` but didn't have a macro for `\vdots`, so must have just been force of habit.

**Comment by imagine-hussain** [comment]
> ![image](https://user-images.githubusercontent.com/112688727/222960003-89ca149c-9509-46bf-90a9-f923f5a7a530.png) Should there be full stops here? Also Taylor's Theorem has f(n)(a) not f(n)(x) in the sum. I believe the remainder has (x−a)k+1 instead of (x−a)k.

Thats right! Fixed.

**Comment by imagine-hussain** [comment]
Thank you @jeremyle56 for all the suggestions. I type these up during lectures and usually don't edit them after so some mistakes tend to slip through. I've pushed fixes for all of these out now, so at-least the first three weeks should now be correct.

I'm going to close this issue now but, feel free to open up another for future weeks if you find more mistakes.
